ALTER TABLE guests
ADD COLUMN email TEXT DEFAULT '';

CREATE TABLE IF NOT EXISTS blacklist (
	id INTEGER PRIMARY KEY,
    email TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS whitelist (
	id INTEGER PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    passcode TEXT NOT NULL
);