ALTER TABLE party
ADD COLUMN admin_email TEXT NOT NULL DEFAULT '';

ALTER TABLE party
ADD COLUMN user_code TEXT NOT NULL DEFAULT '';

ALTER TABLE party
ADD COLUMN admin_code TEXT NOT NULL DEFAULT '';